[build]
builder = "NIXPACKS"
nixpacksPlan = ""

[build.nixpacksPlanConfig]
providers = ["node"]
buildCommand = "pnpm install --no-frozen-lockfile && pnpm --filter api-server build"

[deploy]
startCommand = "node api-server/dist/index.mjs"

[nixpacks]
aptPkgs = []
nixPkgs = ["nodejs_20", "nodePackages.pnpm"
